name: SleepyWalton
options:
  minimumXcodeGenVersion: 2.38.0
configs:
  Debug: debug
  Release: release
targets:
  SleepyWalton:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Sources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.sleepywalton.app
      INFOPLIST_FILE: Sources/Info.plist
      SWIFT_VERSION: 5.0
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 0.1.0
    scheme:
      testTargets: []
packages: {}